version: "3"
services:
  back:
    image: ven_test_back:dev
    restart: unless-stopped
    build: ./back
    volumes:
      - "./back:/var/www/html"
      - "./mail/build:/var/www/html/mail"
    ports:
      - "127.0.0.1:85:80"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SMTP_FROM: ${SMTP_FROM}
      SMTP_NAME: ${SMTP_NAME}
    links:
      - database:database

  database:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - "./database/scripts:/docker-entrypoint-initdb.d"
      - "./database/data:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  front:
    image: front:dev
    restart: unless-stopped
    build: ./front
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - WDS_SOCKET_PORT=0
    volumes:
      - ./front/src:/app/src
      - ./front/package.json:/app/package.json
      - ./front/package-lock.json:/app/package-lock.json
      - ./front/public:/app/public
    depends_on:
      - back
      
  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    links:
      - front:front
      - back:back